# Generated by Django 3.1.14 on 2022-06-07 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20220607_1106'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml', '0006_dbmlbackend'),
        ('tasks', '0016_auto_20220414_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDbTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.TextField(blank=True, max_length=400, null=True, verbose_name='标注原始文本')),
                ('auto', models.JSONField(blank=True, max_length=400, null=True, verbose_name='算法计算')),
                ('manual', models.JSONField(blank=True, max_length=400, null=True, verbose_name='手动标注')),
                ('confidence', models.FloatField(null=True, verbose_name='可信度')),
                ('remarks', models.TextField(blank=True, max_length=400, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time a task was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time a task was updated', verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tag', to=settings.AUTH_USER_MODEL)),
                ('db_backend', models.ForeignKey(help_text='Project ID for this task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_tag', to='ml.dbmlbackend')),
                ('project', models.ForeignKey(help_text='Project ID for this task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tag', to='projects.project')),
                ('task', models.ForeignKey(help_text='Corresponding task for this annotation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_tag', to='tasks.task')),
                ('updated_by', models.ForeignKey(help_text='Last annotator or reviewer who updated this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tag', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
        ),
    ]
