# Generated by Django 3.1.14 on 2022-06-15 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0006_dbmlbackend'),
        ('projects', '0017_auto_20220607_1106'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0017_taskdbtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDbAlgorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.JSONField(blank=True, max_length=400, null=True, verbose_name='原始文本')),
                ('algorithm', models.JSONField(blank=True, null=True, verbose_name='算法清洗')),
                ('manual', models.JSONField(blank=True, null=True, verbose_name='手动标注')),
                ('remarks', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time a task was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time a task was updated', verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tag', to=settings.AUTH_USER_MODEL)),
                ('db_backend', models.ForeignKey(help_text='Project ID for this task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_tag', to='ml.dbmlbackend')),
                ('project', models.ForeignKey(help_text='Project ID for this task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tag', to='projects.project')),
                ('task', models.ForeignKey(help_text='Corresponding task for this annotation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_tag', to='tasks.task')),
                ('updated_by', models.ForeignKey(help_text='Last annotator or reviewer who updated this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tag', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskDbTag',
        ),
    ]
