# Generated by Django 3.1.14 on 2022-06-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_auto_20220615_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdbalgorithm',
            name='state',
            field=models.IntegerField(choices=[(0, 'initial'), (1, 'ongoing'), (2, 'success'), (3, 'fail')], default=0, verbose_name='状态'),
        ),
    ]
