# Generated by Django 3.1.14 on 2022-07-07 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0006_dbmlbackend'),
        ('projects', '0019_auto_20220617_0206'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0020_taskdbalgorithm_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdbalgorithm',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clean', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskdbalgorithm',
            name='db_backend',
            field=models.ForeignKey(help_text='Project ID for this task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_clean', to='ml.dbmlbackend'),
        ),
        migrations.AlterField(
            model_name='taskdbalgorithm',
            name='project',
            field=models.ForeignKey(help_text='Project ID for this task', on_delete=django.db.models.deletion.CASCADE, related_name='project_clean', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='taskdbalgorithm',
            name='task',
            field=models.ForeignKey(help_text='Corresponding task for this annotation', on_delete=django.db.models.deletion.CASCADE, related_name='task_clean', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='taskdbalgorithm',
            name='updated_by',
            field=models.ForeignKey(help_text='Last annotator or reviewer who updated this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_clean', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.CreateModel(
            name='TaskDbAlgorithmDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.JSONField(blank=True, max_length=400, null=True, verbose_name='原始文本')),
                ('manual', models.JSONField(blank=True, null=True, verbose_name='手动标注')),
                ('state', models.IntegerField(choices=[(0, 'initial'), (1, 'ongoing'), (2, 'success'), (3, 'fail')], default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time a task was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time a task was updated', verbose_name='updated at')),
                ('algorithm', models.ForeignKey(blank=True, help_text='Corresponding Algorithm for this draft', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='tasks.taskdbalgorithm')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clean_draft', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Corresponding task for this annotation', on_delete=django.db.models.deletion.CASCADE, related_name='task_clean_draft', to='tasks.task')),
                ('updated_by', models.ForeignKey(help_text='Last annotator or reviewer who updated this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_clean_draft', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(help_text='Draft result in JSON format', verbose_name='result')),
                ('score', models.FloatField(default=None, help_text='Prediction score', null=True, verbose_name='score')),
                ('model_version', models.TextField(blank=True, default='', null=True, verbose_name='model version')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
                ('backups_created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time', verbose_name='created at')),
                ('backups_created_by', models.ForeignKey(help_text='User who created this draft', on_delete=django.db.models.deletion.CASCADE, related_name='pre_draft', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, help_text='Corresponding task for this draft', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_draft', to='tasks.task')),
            ],
        ),
    ]
