# Generated by Django 3.1.14 on 2022-07-07 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_auto_20220707_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictiondraft',
            name='backups_created_at',
        ),
        migrations.RemoveField(
            model_name='predictiondraft',
            name='backups_created_by',
        ),
    ]
