# Generated by Django 3.1.14 on 2022-07-08 03:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20220617_0206'),
        ('tasks', '0022_auto_20220707_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdbalgorithmdraft',
            name='project',
            field=models.ForeignKey(default=146, help_text='Project ID for this'
                                                         ' task', on_delete=django.db.models.deletion.CASCADE, related_name='project_clean_draft', to='projects.project'),
            preserve_default=False,
        ),
    ]
