# Generated by Django 3.1.14 on 2022-07-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_taskdbalgorithmdraft_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdbalgorithmdraft',
            name='algorithm',
        ),
    ]
