# Generated by Django 3.1.14 on 2022-11-08 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0017_auto_20221108_0550'),
        ('tasks', '0026_prediction_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLabelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(default=dict, help_text='Prediction result', null=True, verbose_name='result')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('model', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model_manager.modelmanager')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'db_table': 'prediction_history',
            },
        ),
    ]
