version: "3.3"

services:
  nginx:
    image: nginx:1.21
    ports:
      - "8082:80"
      #- "8081:443"
    depends_on:
      - app
    environment:
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - NGINX_FILE=${NGINX_FILE:-default.conf}
#   Optional: Specify SSL termination certificate & key
#   Just drop your cert.pem and cert.key into folder 'deploy/nginx/certs'
#      - NGINX_SSL_CERT=/certs/cert.pem
#      - NGINX_SSL_CERT_KEY=/certs/cert.key
    volumes:
      # keep in sync with deploy/docker-entrypoint.d/30-copy-static-data.sh
      - source: static
        target: /label-studio/label_studio
        type: volume
        volume:
          nocopy: true
      - ./label-data:/label-studio/data:rw
      - ./deploy/nginx/${NGINX_FILE:-default.conf}:/etc/nginx/templates/${NGINX_FILE:-default.conf}.template
      - ./deploy/nginx/scripts:/docker-entrypoint.d/label-studio
      - ./deploy/nginx/certs:/certs:ro
    command: nginx -g "daemon off;"

  app:
    stdin_open: true
    tty: true
    build: .
    image: containers.git.digitalbrain.cn/engineering-group/label-studio:development
    expose:
      - "8080"
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=Dbtest
      - POSTGRE_PORT=5432
      #- POSTGRE_HOST=192.168.0.92
      - POSTGRE_HOST=124.71.161.146
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - LABEL_STUDIO_COPY_STATIC_DATA=true
    volumes:
      - ./label-data:/label-studio/data:rw
      # keep in sync with deploy/docker-entrypoint.d/30-copy-static-data.sh
      - source: static
        target: /label-studio/static_volume
        type: volume
        volume:
          nocopy: true

volumes:
  static: {}
