title: Intent Classification for Dialog
type: community
group: Digital Brain
image: /static/templates/intent-classification-and-slot-filling.png
details: <h1>Build task-oriented dialogue system by selecting dialogue intents and extracting slot entities</h1>
config: |
  <View className="template-intent-classification-for-dialog">
    <Paragraphs name="dialogue" value="$dialogue" layout="dialogue" />
    <Choices name="intent" toName="dialogue" choice="multiple" showInLine="true">
      <Choice value="升级"/>
      <Choice value="不知情"/>
      <Choice value="外呼"/>
    </Choices>
  </View>
