# Generated by Django 3.1.14 on 2022-07-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20211010_1339'),
        ('model_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelmanager',
            unique_together={('organization_id', 'title')},
        ),
    ]
