# Generated by Django 3.1.14 on 2022-07-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_template_type'),
        ('organizations', '0003_auto_20211010_1339'),
        ('model_manager', '0002_auto_20220725_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmanager',
            name='project_set',
            field=models.ForeignKey(blank=True, help_text='项目集合', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_config_project_set', to='projects.projectset'),
        ),
        migrations.AlterField(
            model_name='modelmanager',
            name='title',
            field=models.CharField(help_text='Model set name. ', max_length=20, verbose_name='title'),
        ),
        migrations.AlterUniqueTogether(
            name='modelmanager',
            unique_together={('organization_id', 'title', 'version')},
        ),
        migrations.RemoveField(
            model_name='modelmanager',
            name='model',
        ),
    ]
