# Generated by Django 3.1.14 on 2022-08-03 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20220803_0259'),
        ('organizations', '0005_auto_20220728_0623'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model_manager', '0004_auto_20220728_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.JSONField(blank=True, null=True, verbose_name='remark')),
                ('rate', models.FloatField(blank=True, default=0, null=True, verbose_name='rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_record', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_record', to='model_manager.modelmanager')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_record_org', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_record_project', to='projects.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_record', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
        ),
    ]
