# Generated by Django 3.1.14 on 2022-08-04 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0005_modelrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmanager',
            name='model',
            field=models.ForeignKey(blank=True, help_text='训练用的基础模型', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_config', to='model_manager.modelmanager'),
        ),
    ]
