# Generated by Django 3.1.14 on 2022-08-22 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0006_modelmanager_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelrecord',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='modelrecord',
            name='remark',
        ),
        migrations.AddField(
            model_name='modelrecord',
            name='accuracy_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='accuracy rate'),
        ),
        migrations.AddField(
            model_name='modelrecord',
            name='exactness',
            field=models.IntegerField(default=0, verbose_name='exactness annotation'),
        ),
        migrations.AddField(
            model_name='modelrecord',
            name='is_train',
            field=models.BooleanField(default=False, verbose_name='train'),
        ),
        migrations.AddField(
            model_name='modelrecord',
            name='new_accuracy_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='new accuracy rate'),
        ),
        migrations.AddField(
            model_name='modelrecord',
            name='new_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model_manager.modelmanager'),
        ),
        migrations.AddField(
            model_name='modelrecord',
            name='new_model_assessment_task',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='modelrecord',
            name='new_model_train_task',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='modelrecord',
            name='total',
            field=models.IntegerField(default=0, verbose_name='total task'),
        ),
        migrations.AddField(
            model_name='modelrecord',
            name='training_progress',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
