# Generated by Django 3.1.14 on 2022-08-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0007_auto_20220822_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelrecord',
            name='exactness',
        ),
        migrations.RemoveField(
            model_name='modelrecord',
            name='total',
        ),
        migrations.AddField(
            model_name='modelrecord',
            name='category',
            field=models.CharField(choices=[('train', '训练'), ('assessment', '评估')], default=0, max_length=15, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelrecord',
            name='exactness_count',
            field=models.IntegerField(default=0, verbose_name='exactness annotation'),
        ),
        migrations.AddField(
            model_name='modelrecord',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='total task'),
        ),
    ]
