# Generated by Django 3.1.14 on 2022-08-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0008_auto_20220823_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrecord',
            name='exactness_count',
            field=models.IntegerField(default=0, null=True, verbose_name='exactness annotation'),
        ),
        migrations.AlterField(
            model_name='modelrecord',
            name='total_count',
            field=models.IntegerField(default=0, null=True, verbose_name='total task'),
        ),
    ]
