# Generated by Django 3.1.14 on 2022-08-24 09:24

import core.utils.common
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_auto_20220728_0623'),
        ('projects', '0025_project_annotator'),
        ('model_manager', '0009_auto_20220823_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exactness_count', models.IntegerField(default=0, null=True, verbose_name='exactness annotation')),
                ('total_count', models.IntegerField(default=0, null=True, verbose_name='total task')),
                ('is_train', models.BooleanField(default=False, verbose_name='train')),
                ('accuracy_rate', models.FloatField(blank=True, default=0, null=True, verbose_name='accuracy rate')),
                ('new_accuracy_rate', models.FloatField(blank=True, default=0, null=True, verbose_name='new accuracy rate')),
                ('new_model_train_task', models.IntegerField(blank=True, default=None, null=True, verbose_name='')),
                ('new_model_assessment_task', models.IntegerField(blank=True, default=None, null=True, verbose_name='')),
                ('training_progress', models.FloatField(blank=True, default=None, null=True, verbose_name='')),
                ('category', models.CharField(choices=[('train', '训练'), ('assessment', '评估')], max_length=15, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('state', models.IntegerField(choices=[(1, '初始'), (2, '评估'), (3, '训练'), (4, '完成'), (5, '异常')], default=1, null=True, verbose_name='model state')),
                ('model_parameter', models.JSONField(default=dict, help_text='模型入参数', null=True, verbose_name='run model parameter')),
                ('model_result', models.CharField(default='', help_text='模型训练结果URL', max_length=140, null=True, verbose_name='run model result url')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_record', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
        ),
        migrations.AlterField(
            model_name='modelmanager',
            name='state',
            field=models.IntegerField(choices=[(1, '初始'), (2, '评估'), (3, '训练'), (4, '完成'), (5, '异常')], default=1, null=True, verbose_name='model state'),
        ),
        migrations.AlterField(
            model_name='modelmanager',
            name='token',
            field=models.CharField(blank=True, default=core.utils.common.create_hash, max_length=65, null=True, verbose_name='token'),
        ),
        migrations.DeleteModel(
            name='ModelRecord',
        ),
        migrations.AddField(
            model_name='modeltrain',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_record', to='model_manager.modelmanager'),
        ),
        migrations.AddField(
            model_name='modeltrain',
            name='new_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model_manager.modelmanager'),
        ),
        migrations.AddField(
            model_name='modeltrain',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_record_org', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='modeltrain',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_record_project', to='projects.project'),
        ),
        migrations.AddField(
            model_name='modeltrain',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_record', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
    ]
