# Generated by Django 3.1.14 on 2022-08-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_taskdbalgorithmdraft_algorithm'),
        ('model_manager', '0010_auto_20220824_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltrain',
            name='new_model_assessment_task',
        ),
        migrations.RemoveField(
            model_name='modeltrain',
            name='new_model_train_task',
        ),
        migrations.AddField(
            model_name='modeltrain',
            name='assessment_task',
            field=models.ManyToManyField(related_name='model_assessment', to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='modeltrain',
            name='train_task',
            field=models.ManyToManyField(related_name='model_train', to='tasks.Task'),
        ),
    ]
