# Generated by Django 3.1.14 on 2022-08-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0012_auto_20220825_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrain',
            name='model_title',
            field=models.CharField(default='', help_text='Model name. ', max_length=20, verbose_name='title'),
            preserve_default=False,
        ),
    ]
