# Generated by Django 3.1.14 on 2022-08-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0013_modeltrain_model_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmanager',
            name='url',
            field=models.TextField(help_text='URL for the machine learning model server', verbose_name='url'),
        ),
    ]
