# Generated by Django 3.1.14 on 2022-09-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0014_auto_20220830_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrain',
            name='train_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='finished at'),
        ),
    ]
