# Generated by Django 3.1.14 on 2022-11-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0015_modeltrain_train_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmanager',
            name='type',
            field=models.CharField(choices=[('intention', '对话意图分类'), ('generation', '对话生成'), ('correction', '轮次纠正'), ('intelligent', '智能清洗'), ('rule', '规则清洗')], default=None, max_length=50, null=True, verbose_name='model type'),
        ),
    ]
