# Generated by Django 3.1.14 on 2022-11-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_prediction_model'),
        ('model_manager', '0016_auto_20221102_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltrain',
            name='assessment_task',
            field=models.ManyToManyField(blank=True, default=None, related_name='model_assessment', to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='modeltrain',
            name='train_task',
            field=models.ManyToManyField(blank=True, default=None, related_name='model_train', to='tasks.Task'),
        ),
    ]
