# Generated by Django 3.1.14 on 2022-11-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0017_auto_20221108_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrain',
            name='remark',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='备注/说明'),
        ),
        migrations.AlterField(
            model_name='modelmanager',
            name='state',
            field=models.IntegerField(choices=[(1, '初始'), (2, '评估'), (3, '训练'), (4, '完成'), (5, '失败'), (6, '运行中')], default=1, null=True, verbose_name='model state'),
        ),
        migrations.AlterField(
            model_name='modeltrain',
            name='category',
            field=models.CharField(choices=[('train', '训练'), ('assessment', '评估'), ('model', '模型')], max_length=15, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='modeltrain',
            name='state',
            field=models.IntegerField(choices=[(1, '初始'), (2, '评估'), (3, '训练'), (4, '完成'), (5, '失败'), (6, '运行中')], default=1, null=True, verbose_name='model state'),
        ),
    ]
