# Generated by Django 3.1.14 on 2022-12-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0018_auto_20221118_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelmanager',
            name='project_set',
        ),
        migrations.RemoveField(
            model_name='modelmanager',
            name='token',
        ),
        migrations.AddField(
            model_name='modelmanager',
            name='hash_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='hash_id'),
        ),
        migrations.AlterField(
            model_name='modelmanager',
            name='type',
            field=models.CharField(choices=[('intention', '预标注-0样本'), ('annotation', '预标注-普通'), ('dialogue', '对话生成-普通'), ('dialogue_prompt', '对话生成-0样本'), ('bart_for_turn', '轮次纠正'), ('intelligent', '智能清洗'), ('rule', '规则清洗')], default=None, max_length=50, null=True, verbose_name='model type'),
        ),
    ]
