# Generated by Django 3.1.14 on 2022-12-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0020_auto_20221220_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelmanager',
            name='description',
        ),
        migrations.AddField(
            model_name='modelmanager',
            name='labels',
            field=models.TextField(blank=True, default='', null=True, verbose_name='labels'),
        ),
    ]
