# Generated by Django 3.1.14 on 2022-12-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0021_auto_20221220_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmanager',
            name='base',
            field=models.BooleanField(default=False, verbose_name='base'),
        ),
        migrations.AlterField(
            model_name='modelmanager',
            name='state',
            field=models.IntegerField(choices=[(1, '初始'), (2, '评估'), (3, '训练中'), (4, '已完成'), (5, '失败'), (6, '运行中')], default=1, null=True, verbose_name='model state'),
        ),
        migrations.AlterField(
            model_name='modeltrain',
            name='state',
            field=models.IntegerField(choices=[(1, '初始'), (2, '评估'), (3, '训练中'), (4, '已完成'), (5, '失败'), (6, '运行中')], default=1, null=True, verbose_name='model state'),
        ),
    ]
