# Generated by Django 3.1.14 on 2022-12-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0022_auto_20221221_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmanager',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='delete'),
        ),
    ]
