# Generated by Django 3.1.14 on 2022-12-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0023_modelmanager_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmanager',
            name='model_type',
            field=models.CharField(choices=[('intention', '对话意图分类'), ('generation', '对话生成'), ('correction', '轮次纠正'), ('intelligent', '智能清洗'), ('rule', '规则清洗')], default=None, max_length=50, null=True, verbose_name='模型类型（产品）说明'),
        ),
        migrations.AlterField(
            model_name='modelmanager',
            name='type',
            field=models.CharField(choices=[('intention', '预标注-0样本'), ('annotation', '预标注-普通'), ('dialogue', '对话生成-普通'), ('dialogue_prompt', '对话生成-0样本'), ('bart_for_turn', '轮次纠正'), ('intelligent', '智能清洗'), ('rule', '规则清洗')], default=None, max_length=50, null=True, verbose_name='算法类型说明'),
        ),
    ]
