# Generated by Django 3.1.14 on 2022-12-27 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0024_auto_20221221_0843'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelmanager',
            unique_together=set(),
        ),
    ]
