title: Conversational AI - Response Generation
type: community
group: Digital Brain
image: /static/templates/response-generation.png
details: <h1>Collect chatbot training data by generating next dialogue response</h1>
config: |
  <View className="template-conversational-ai-response-generation">
    <Paragraphs name="chat" value="$dialogue" layout="dialogue"/>
    <Header value="意图标签"/>
    <Choices readonly="true" name="intent" toName="chat" choice="multiple" showInLine="true">
      <Choice value="升级"/>
      <Choice value="不知情"/>
      <Choice value="外呼"/>
    </Choices>
    <Header value="提供对话"/>
    <TextArea name="response" toName="chat" rows="4" editable="true" maxSubmissions="100"/>
  </View>

