title: Conversational AI - Response Generation
type: community
group: Digital Brain
image: /static/templates/response-generation.png
details: <h1>Collect chatbot training data by generating next dialogue response</h1>
config: |
  <View className="template-conversational-ai-response-generation">
    <Paragraphs name="chat" value="$dialogue" layout="dialogue"/>
    <Header value="意图标签" size="4"/>
    <Header value="升级" size="5"/>
    <TextArea name="升级" toName="chat" rows="4" editable="true" maxSubmissions="100"/>
    <Header value="不升级" size="5"/>
    <TextArea name="不升级" toName="chat" rows="4" editable="true" maxSubmissions="100"/>
  </View>
