# Generated by Django 3.1.14 on 2022-08-10 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='菜单标题')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='菜单别名')),
                ('path', models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单路径')),
                ('icon', models.CharField(blank=True, max_length=40, null=True, verbose_name='图标')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('project', models.CharField(blank=True, max_length=30, null=True, verbose_name='项目')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmspage_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('group', models.ManyToManyField(blank=True, related_name='pms_group', to='auth.Group', verbose_name='组')),
                ('user', models.ManyToManyField(blank=True, related_name='pms_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '菜单页面',
                'verbose_name_plural': '菜单页面',
                'db_table': 'pms_page',
            },
        ),
        migrations.CreateModel(
            name='PmsButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=20)),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('group', models.ManyToManyField(blank=True, related_name='pms_btn_group', to='auth.Group', verbose_name='组')),
                ('page', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pms_btn_page', to='pms.pmspage', verbose_name='页面')),
                ('user', models.ManyToManyField(blank=True, related_name='pms_btn_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '菜单页面按键',
                'verbose_name_plural': '菜单页面按键',
                'db_table': 'pms_page_button',
                'unique_together': {('page', 'code')},
            },
        ),
    ]
