# Generated by Django 3.1.14 on 2022-06-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_taskdbalgorithm_state'),
        ('projects', '0017_auto_20220607_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.JSONField(blank=True, max_length=1000, null=True, verbose_name='模版')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time a task was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time a task was updated', verbose_name='updated at')),
                ('project', models.ForeignKey(help_text='Project ID for this task', on_delete=django.db.models.deletion.CASCADE, related_name='project_PromptTemplates_id', to='projects.project')),
                ('task', models.ForeignKey(help_text='Corresponding task for this annotation', on_delete=django.db.models.deletion.CASCADE, related_name='task_id', to='tasks.task')),
            ],
            options={
                'unique_together': {('project_id', 'task_id', 'template')},
            },
        ),
        migrations.CreateModel(
            name='PromptResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField(blank=True, max_length=1000, null=True, verbose_name='模型输出')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time a task was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time a task was updated', verbose_name='updated at')),
                ('project', models.ForeignKey(help_text='Project ID for this task', on_delete=django.db.models.deletion.CASCADE, related_name='project_PromptResult_id', to='projects.project')),
                ('task', models.ForeignKey(help_text='Corresponding task for this annotation', on_delete=django.db.models.deletion.CASCADE, related_name='task_PromptResult_id', to='tasks.task')),
            ],
            options={
                'unique_together': {('project_id', 'task_id')},
            },
        ),
    ]
