# Generated by Django 3.1.14 on 2022-06-17 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_taskdbalgorithm_state'),
        ('projects', '0018_promptresult_prompttemplates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promptresult',
            unique_together={('task_id', 'project_id', 'metrics')},
        ),
        migrations.AlterUniqueTogether(
            name='prompttemplates',
            unique_together={('project_id', 'template')},
        ),
        migrations.RemoveField(
            model_name='prompttemplates',
            name='task',
        ),
    ]
