# Generated by Django 3.1.14 on 2022-07-14 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_taskdbalgorithmdraft_algorithm'),
        ('projects', '0019_auto_20220617_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptResultDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField(blank=True, max_length=1000, null=True, verbose_name='模型输出')),
                ('created_at', models.DateTimeField(blank=True, help_text='Time a task was created', null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, help_text='Last time a task was updated', null=True, verbose_name='updated at')),
                ('project', models.ForeignKey(help_text='Project ID for this task', on_delete=django.db.models.deletion.CASCADE, related_name='project_PromptResultDraft_id', to='projects.project')),
                ('task', models.ForeignKey(help_text='Corresponding task for this annotation', on_delete=django.db.models.deletion.CASCADE, related_name='task_PromptResultDraft_id', to='tasks.task')),
            ],
        ),
    ]
