# Generated by Django 3.1.14 on 2022-07-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_projectset'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='set',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='project_set', to='projects.projectset'),
        ),
    ]
