# Generated by Django 3.1.14 on 2022-07-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_project_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='template_type'),
        ),
    ]
