# Generated by Django 3.1.14 on 2022-11-04 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0016_auto_20221102_0256'),
        ('projects', '0025_project_annotator'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='model_manager.modelmanager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='template_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='项目类型（名字不好改回去）'),
        ),
    ]
