# Generated by Django 3.1.14 on 2022-11-07 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0026_auto_20221104_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='annotator',
            field=models.ManyToManyField(blank=True, default=None, related_name='org_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
