# Generated by Django 3.1.14 on 2022-11-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20221107_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplates',
            name='label',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='标签'),
        ),
    ]
