# Generated by Django 3.1.14 on 2022-11-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_prompttemplates_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplates',
            name='label',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='标签'),
        ),
        migrations.AlterUniqueTogether(
            name='prompttemplates',
            unique_together={('project_id', 'template', 'label')},
        ),
    ]
