# Generated by Django 3.1.14 on 2022-07-20 07:31

import core.mixins
import core.utils.common
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_auto_20211010_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfiger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Model name.', max_length=200, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', help_text='model configer description', null=True, verbose_name='description')),
                ('token', models.CharField(blank=True, default=core.utils.common.create_hash, max_length=65, null=True, unique=True, verbose_name='token')),
                ('model_set', models.CharField(blank=True, max_length=180, null=True, verbose_name='model set')),
                ('version', models.TextField(blank=True, default='', help_text='Machine learning model version', null=True, verbose_name='model version')),
                ('type', models.CharField(choices=[('dialog intention', '对话意图分类'), ('Dialog generation', '对话生成'), ('clean', '清洗模型'), ('other', '其他')], default='other', max_length=50, null=True, verbose_name='model type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_model', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_configer', to='organizations.organization')),
            ],
            bases=(core.mixins.DummyModelMixin, models.Model),
        ),
    ]
