# Generated by Django 3.1.14 on 2022-07-20 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_promptresultdraft'),
        ('model_configer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelconfiger',
            name='model_set',
        ),
        migrations.AddField(
            model_name='modelconfiger',
            name='model',
            field=models.ForeignKey(blank=True, help_text='训练用的基础模型', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_config', to='model_configer.modelconfiger'),
        ),
        migrations.AddField(
            model_name='modelconfiger',
            name='project',
            field=models.ForeignKey(blank=True, help_text='训练用的项目', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_config_project', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='modelconfiger',
            name='type',
            field=models.CharField(choices=[('intention', '对话意图分类'), ('generation', '对话生成'), ('clean', '清洗模型'), ('other', '其他')], default='other', max_length=50, null=True, verbose_name='model type'),
        ),
    ]
