# Generated by Django 3.1.14 on 2022-07-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_configer', '0002_auto_20220720_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfiger',
            name='url',
            field=models.TextField(default='www.baidu.com/api/v2.0', help_text='URL for the machine learning model server', unique=True, verbose_name='url'),
            preserve_default=False,
        ),
    ]
