# Generated by Django 3.1.14 on 2022-07-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20220728_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='organization title'),
        ),
    ]
